services:
  ros2:
    runtime: nvidia
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility,display
      __NV_PRIME_RENDER_OFFLOAD: "1"
      __NV_PRIME_RENDER_OFFLOAD_PROVIDER: NVIDIA-G0
      __GLX_VENDOR_LIBRARY_NAME: nvidia
      __VK_LAYER_NV_optimus: NVIDIA_only
    devices:
      - /dev/dri:/dev/dri
