services:
  ros2:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: tsukuba2025:latest
    container_name: tsukuba2025_navigation
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    volumes:
      - ./navigation_ws:/home/user/navigation_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/user/navigation_ws
    tty: true
    stdin_open: true
